// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4lZgatGzPXJcrnt2GA8Oftt1Hs-Tls7k',
    appId: '1:475201429605:web:f0dc0c3554d352ea8d668c',
    messagingSenderId: '475201429605',
    projectId: 'simplecrudff',
    authDomain: 'simplecrudff.firebaseapp.com',
    storageBucket: 'simplecrudff.appspot.com',
    measurementId: 'G-LQS9M9LZRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8N4AupbZFwCtgt-fKSMPkH7jPiWBvdaY',
    appId: '1:475201429605:android:4b0fe2f0de8ff9048d668c',
    messagingSenderId: '475201429605',
    projectId: 'simplecrudff',
    storageBucket: 'simplecrudff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDChEAYcSRVlJvxkWMxx_hp80hKTTQEzlg',
    appId: '1:475201429605:ios:c53260bc066786428d668c',
    messagingSenderId: '475201429605',
    projectId: 'simplecrudff',
    storageBucket: 'simplecrudff.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDChEAYcSRVlJvxkWMxx_hp80hKTTQEzlg',
    appId: '1:475201429605:ios:d2c45ece0fa23ecd8d668c',
    messagingSenderId: '475201429605',
    projectId: 'simplecrudff',
    storageBucket: 'simplecrudff.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
